### ISSUE TITLE
Compressor causing frame lag

### ISSUE THREAD

**Issue by Zetharion** [p455w0rd/p455w0rd-s-Things#10]
Was watching Weallplaycast test out an alpha modpack called Hypothermia for 1.10.2  He placed down the Compressor and his frames immediately tanked to low single digits.  Broke the Compressor and they shot back up to normal.

Library version is 1.0.18
Mod version is 2.0.3

**Comment by p455w0rd** [comment]
yeah I was afraid of something like this..it's an alpha of my mod so I can fix it, but it won't be updated for a while because I'm rewriting a good portion of the code

**Comment by p455w0rd** [comment]
thanks for the report btw :)

**Comment by Zetharion** [comment]
No problem, Raj asked for someone to report it so that its known.
