### ISSUE TITLE
[Alpha] Universal Cables Power

### ISSUE THREAD

**Issue by YOYOK9** [p455w0rd/p455w0rd-s-Things#18]
Mekanism universal cable can export power into the tesseract but the tesseract can't export rf through a universal cable to a powered block. Will directly power the mekanism machine if placed beside without cables. Tested with all 4 types of cables.

Mekanism/tools/generators: 1.10.2-9.2.2.301

**Comment by p455w0rd** [comment]
Consolidated in #25
