### ISSUE TITLE
Tinkers construct textures not found

### ISSUE THREAD

**Issue by GuntherDW** [p455w0rd/p455w0rd-s-Things#2]
I updated the mod in my pack from 1.10.2-1.2.25 to 1.10.2-1.2.27, and noticed that Carbon textures for Tinkers tools are either missing or corrupted.
They're showing their "texture not found" texture.

The jars are downloaded from their respective curseforge pages.

Screenshot : http://i.imgur.com/LUPQqZZ.png

If I should attach a log to this let me know and I'll upload the log to pastebin. On first glance I don't see anything that has to do with the carbon texture from your mod though, at least nothing that's throwing an exception or not finding its resource.

Versions : 
- Forge : 12.18.3.2185
- Minecraft : 1.10.2
- p455w0rd's Library : 1.9.4-1.0.3
- p455w0rd's Things : 1.10.2-1.2.27
- Tinkers Construct : 1.10.2-2.6.1

**Comment by p455w0rd** [comment]
Nope..I am aware of this :) It's been fixed and will be included in the coming massive update. Thanks for making the issue!

**Comment by meelock** [comment]
hey speaking of, I got a crash report: having to do with "portal 2" particle. i can share it on a new post if you want.

**Comment by meelock** [comment]
java.lang.NullPointerException: Rendering Particle.

**Comment by meelock** [comment]
when i went the the nether

**Comment by meelock** [comment]
something-something ExtendedBlockStorage.

**Comment by meelock** [comment]
semi-complete log: http://pastebin.com/8HjkXg2s, I can upload the full log later.

**Comment by meelock** [comment]
i think the crash has to do with the nether ore.

**Comment by p455w0rd** [comment]
1) Always open a new issue if it is indeed a new issue.
2) Messages are editable, not need to spam so many messages to convey a single thought. This isn't Twitter.
3) This has nothing to do with Nether Carbon Ore. ParticlePortal2 is the green Enderman particles (the Particle part kind of gives that away). This will be fixed in the next update. Please open a new issue still for tracking purposes.

**Comment by p455w0rd** [comment]
Okay, so the offending method is where my particle gets the light level for an individual particle. It is not possible for numerical variables to return null. In Java, at worst, they return 0, 0.0D, or 0.0F. I'm not sure how this would happen unless another mod is modifying vanilla functionality as my particle code is a 100% copy of the vanilla version, with the only change being the color from purple to green. I've also tested in an environment with p455w0rd's Things, Bontania, Baubles, EnderIO, JEI, WAILA, and TOP and I can traverse dimensions fine.
