### ISSUE TITLE
[Alpha] Extrautiles crash

### ISSUE THREAD

**Issue by YOYOK9** [p455w0rd/p455w0rd-s-Things#21]
https://pastebin.com/52iamnhk

While using extra utiles2 fluid transfer pipes taking water from a 2x2 water source and trying to put itt into a enderio tank using tesseracts

extrautils2-1.10.2-1.4

**Comment by p455w0rd** [comment]
thanks :)

**Comment by YOYOK9** [comment]
as an extra note. the fluid goes into the tess but doesn't come back out. the Tess "eats" it (void)
