### ISSUE TITLE
[Alpha] Enderio tanks

### ISSUE THREAD

**Issue by YOYOK9** [p455w0rd/p455w0rd-s-Things#22]
Can't extract fluid from ender io tanks pushing  into the tess. Since ender io tanks can push their fluids into adjacent inventories.

**Comment by p455w0rd** [comment]
this is a limitation of how it functions..for items and fluid you MUST pipe in and on the receiving end, you MUST have the receiving inventory adjacent to the interchanger...I do plan to change the functionality at some point to more reflect the Tesseract in 1.7.10, but for now, it will at least function correctly using this configuration and does provide a viable solution for those wanting something lik this.
