### ISSUE TITLE
Custom Endermen ignoring light levels on spawning

### ISSUE THREAD

**Issue by SephirothWS** [p455w0rd/p455w0rd-s-Things#28]
Considering they're hostile mobs like regular Endermen, I feel they should not ignore light levels when spawning. In Project Ozone Lite, I'm constantly having to deal with these guys spawning on my island despite it being perfectly lit up to prevent all other spawns.

**Comment by p455w0rd** [comment]
That's the point of them...they also don't teleport due to water...give the curse page a look..also, if you can't take it..there's a config..

**Comment by SephirothWS** [comment]
So the point of them is to be exceedingly annoying and spawning where mobs don't spawn? That's mentioned nowhere on the curse page.
