### ISSUE TITLE
Enderman not effected by Aversion Obelisk

### ISSUE THREAD

**Issue by dabigmoose** [p455w0rd/p455w0rd-s-Things#29]
Not sure if its you or Enderio but when you use soul vial on one of your everspawning enderman they don't obey Aversion obelisk rules.

I used a soul vial to grab one of your enderman and put in obelisk and well they are still spawning in my skyblock. Again I am not sure if it's your mod or Enderio. If it's enderio then please make a way to stop them from spawning via some method, I like the fact they spawn but when your in a long dureation pack they become annoying.

**Comment by p455w0rd** [comment]
nice catch...highly unlikely EnderIO as I have never implicitly added functionality for the obelisks[attractor/aversion] (I've just added recipe compat for EnderIO machines that use my Enderman in Soul Vials)..will look into this as soon as I can
