### ISSUE TITLE
Magnet not draining charge when pulling items/exp

### ISSUE THREAD

**Issue by Monsterrat25** [p455w0rd/p455w0rd-s-Things#3]
While active, magnet pulls in both items and exp without draining its stored RF. It will do the bug with any charge from 1 to 1,000,000 RF (1 being the minimum required to activate it).
- Minecraft1.10.2 forge-12.18.3.2185
- p455w0rdslib-1.10.2-1.0.11
- p455w0rdsthings-1.10.2-1.2.27
If you need a complete mod list let me know. 

(not sure if bug or not implemented yet?)

**Comment by p455w0rd** [comment]
Well, during testing at one point I overrode the extractEnergy method so it always returned 0 lol...it is fixed in next update, thanks for the report :)
