### ISSUE TITLE
Something seems off with the advanced armorstand

### ISSUE THREAD

**Issue by tigerdan2** [p455w0rd/p455w0rd-s-Things#30]
Version : 1.10.2
MP/SP  : Multiplayer 

kinda hard to explain so im adding a vid
https://streamable.com/musht

**Comment by p455w0rd** [comment]
this is definitely very odd behavior..thankfully it doesn't seem like a dupe bug, but rather just a desync...and I knew it was a tad buggy when i finished work on it, but so very few people use it (you are the first person I've heard of that uses it) that I didn't see it as a big deal..the next pwthings release is so close, but life has gotten in the way so I've temporarily halted work on the mod..hopefully I can get a release out sometime this week and I'll look into this then. Thanks for the report :)

**Comment by p455w0rd** [comment]
yeah...sorry...I have to let this die..too many other important things on my plate..I will accept PRs to fix..but I just don't have the time to fix something trivial like this :/
