### ISSUE TITLE
[1.10.2] Crash on Server load with 1.10.2-2.0.23

### ISSUE THREAD

**Issue by DeadSix27** [p455w0rd/p455w0rd-s-Things#31]
Stacktrace: https://gist.github.com/DeadSix27/01a28c189fb893e923e0f04a24a8e3f0

**Comment by p455w0rd** [comment]
will get a hotfix out asap

**Comment by p455w0rd** [comment]
@covers1624 can you weigh in here please?

**Comment by p455w0rd** [comment]
nvm..I think it's just annotations...testing now

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/p455w0rds-things/files/2484875
