### ISSUE TITLE
1.10.2-2.0.25 has hard dependency on EnderStorage

### ISSUE THREAD

**Issue by brisingraerowing** [p455w0rd/p455w0rd-s-Things#32]
I don't use Ender Storage as I have another mod that does the same thing (and has many other things to go with it).

This causes a crash on startup:

[Crash Log](https://gist.github.com/BrisingrAerowing/0a1fb66b7ad7d5b26ebb048789fa7ece)

**Comment by p455w0rd** [comment]
hmmm....there should not be any hard dep with the way I implement dependent mods...I did find an error though...covers has now lower-cased the modid...still the check should definitely return false in this case...will definitely look into it and get a fix out asap...thanks for the report!

**Comment by p455w0rd** [comment]
i rly derped here..found it! :)

**Comment by p455w0rd** [comment]
fixed and approved - https://minecraft.curseforge.com/projects/p455w0rds-things/files
