### ISSUE TITLE
Batteries won't charge in some machines (regression, 1.10.2-2.0.24)

### ISSUE THREAD

**Issue by L-Clouds** [p455w0rd/p455w0rd-s-Things#33]
This is in the context of Project Ozone Lite.

In POLite 1.1.0, which included _p455w0rdslib-1.10.2-1.0.13_ and _p455w0rdsthings-1.10.2-1.2.27_, the normal and emerald Battery items and the Magnet would charge in, for example, EnderIO capacitor blocks, as would the Carbon Jetpack.

In POLite 1.2.0, which includes _p455w0rdslib-1.10.2-1.0.30_ and _p455w0rdsthings-1.10.2-2.0.24_, the normal and emerald Battery items and the Magnet **will not** charge in:
EnderIO capacitor blocks or EnderIO Wireless Charger
nor in Mekanism energy cubes or Mekanism Chargepads

but **will** charge via:
the Draconic Evolution Energy Infuser
the Thermal Expansion Energetic Infuser and by the Thermal Expansion Flux Capacitor item

The Carbon Jetpack and all other armor pieces, however, continue to be charged in ALL of the aforementioned ways.

Some other mods, and the version of Forge, were updated between POLite 1.1.0 and 1.2.0.  However, when I put the updated versions of p455w0rds' mods in an instance of POLite 1.1.0, the same alterations to charging behavior are found, so I believe the issue lies in these mods and not the other mods or in a Forge version incompatibility.

**Comment by p455w0rd** [comment]
this was fixed specifically in p455w0rdsThings-1.10.2-2.0.25 as described in the changelog on CurseForge...I notified Cazador about this, he may have just forgotten to update. I'll remind him. Thanks for the report :)

**Comment by L-Clouds** [comment]
Oh, that's funny.  I saw that but somehow mis-remembered it as coming BEFORE 2.0.24 so I thought maybe that was the source of the issue.  Whoops!
