### ISSUE TITLE
Can't break tile entities without Iron Chests installed (2.2.26, 2.2.27)

### ISSUE THREAD

**Issue by L-Clouds** [p455w0rd/p455w0rd-s-Things#36]
p455w0rdslib-1.10.2-1.0.30 by itself or also with CodeChickenLib-1.10.2-2.5.9.283-universal:
No problems

The above, plus p455w0rdsthings-1.10.2-2.2.27 and ironchest-1.10.2-7.0.15.804:
No problems

But, without Iron Chests:
When breaking a tile entity block, it disappears visually but becomes a ghost block that you can't walk through. After stopping the world and reloading it, the block is actually there again.
[Snippet of the log when trying to break the block](https://gist.github.com/L-Clouds/3c3723dda2bae1968f34ff63d16eb893)

**Comment by Morpheus1101** [comment]
Ghost blocks r usually an indication of a desynch between server and client, hence why relogging fixes them. But if the issue occurs only after ironchests has been installed and cant be re-produced without it having been installed, then id say the issue is with that mod and not this one.

**Comment by p455w0rd** [comment]
lol..ty for trying morph..this is 100% on my end..it happens when iron chests _isn't_ installed :P I was gone doing pirer removal all day, so I haven't been able to get any work done. I'm beat..I dunno if ima do any coding..I will def get this fixed as soon as I have the energy though.

**Comment by L-Clouds** [comment]
Morph...what's morph?  Anyway, NP, and it looks fixed in 2.2.30
