### ISSUE TITLE
Update guide speed upgrade page to reflect diagonal position req

### ISSUE THREAD

**Issue by L-Clouds** [p455w0rd/p455w0rd-s-Things#38]
Minimal test instance:
Forge 2511, CodeChickenLib-1.10.2-2.5.9.283-universal, p455w0rdslib-1.10.2-1.0.30, p455w0rdsthings-1.10.2-2.2.31 (not tested in older versions), single player.

[Two screenshots](https://imgur.com/a/Mc90V)
It doesn't appear to be compressing any faster, and also holy cow that RF drain.  Did I set it up right?

**Comment by Cazadorsniper** [comment]
Speed upgrades need to be diagonal to the compressor

**Comment by p455w0rd** [comment]
one air block away and on the diagonal

**Comment by L-Clouds** [comment]
Ah...ok.  Yeah, they work.  Also, they just hold a lot of RF.

May I suggest that the manual say they should be diagonal?  (I'm pretty sure it doesn't specify.)
