### ISSUE TITLE
emerald bits issue

### ISSUE THREAD

**Issue by EPSIL0N** [p455w0rd/p455w0rd-s-Things#4]
Currently in p455w0rdsthings-1.10.2-1.2.27 your emerald bits are conflicting as they are made with the generic 1 emerald crafts into 9 emerald pieces but you have not attached the oredictionary tag that makes bits crosscompatible with the common nuggetEmerald tagged items.

**Comment by p455w0rd** [comment]
this has been changed in the coming update...there is good reason as to why it's not oreDicted which will be apparent in the coming update

**Comment by EPSIL0N** [comment]
Is there a changelog I could reference as there were other things I wanted to comment about but they may have been addressed already.

**Comment by p455w0rd** [comment]
as the repo the code is hosted on is private atm, no...I plan to transfer the src back to GH after the next update...if u want to chat, you can join me on discord @ https://discord.gg/9J7yhUP ..you can also follow me on twitter where I frequently post screenshots/gifs of current progress
