### ISSUE TITLE
Please update it to 1.12

### ISSUE THREAD

**Issue by hron84** [p455w0rd/p455w0rd-s-Things#41]
Please make this mod available on 1.12 too...

**Comment by p455w0rd** [comment]
Slowly it is happening..I'm taking the most requested features from p455w0rdsThings and making them their own independent 1.12.2 mods. [Join my discord](http://p455w0rd.net/discord) or follow me on [Twitter](https://twitter.com/therealp455w0rd) for updates..I am making progress on this :)

**Comment by hron84** [comment]
@p455w0rd will it include Carbon as a TiCon material?

**Comment by p455w0rd** [comment]
ofc
