### ISSUE TITLE
[suggestion] 16x textures ("pull request" included)

### ISSUE THREAD

**Issue by L-Clouds** [p455w0rd/p455w0rd-s-Things#42]
You have some non-16x textures and item icons.  As a result, they kind of stick out around default vanilla and most other mods' graphics.

For my own enjoyment, I've produced [16x versions of your textures](https://github.com/L-Clouds/p455w0rdsthings-16x-textures), via downsampling and hand-drawing as needed, and I'm offering them to you to include if you want.  There's also the bottom and top layers of the Armor Upgrade icon, in case you will need to make new ones.  I think you'll find they look very close to your original designs.  (Except the door.  I made a new one based on the carbon block texture.)

Furthermore, if you're interested, I also made versions of a few of the [armor upgrades with new animations](https://github.com/L-Clouds/p455w0rdsthings-16x-anims).

**Comment by p455w0rd** [comment]
they aren't that bad..use a resource pack...
