### ISSUE TITLE
 Can I share this mod with the minecraft forum in China?

### ISSUE THREAD

**Issue by 6Bpencle** [p455w0rd/p455w0rd-s-Things#45]
The mod is very interesting ,I very like it.I think you can do it better.So I want to share this mod with the minecraft forum in China.This is website [mcbbs](http://www.mcbbs.net),and let more friends use it.I hope you can agree!

**Comment by p455w0rd** [comment]
so long as the links link to the [official page on CurseForge](https://minecraft.curseforge.com/projects/p455w0rds-things)
