### ISSUE TITLE
Client Crash when Crafting

### ISSUE THREAD

**Issue by jjorstad2** [p455w0rd/p455w0rd-s-Things#51]
Hello I'm having crashing when I try to craft with the Armor Upgrade pieces it dos not seem to mater on the ones I use I get a crash. I have the log below can you please help me out. I was adding your mod to the all the mods mod pack.

[crash-2017-12-15_11.14.52-client.txt](https://github.com/p455w0rd/p455w0rd-s-Things/files/1565031/crash-2017-12-15_11.14.52-client.txt)

**Comment by p455w0rd** [comment]
something's messing with recipes..you have far too many mods in the pack for me to debug and figure out which it is..sorry
